### ISSUE TITLE
Filter grabing clips by game

### ISSUE THREAD

**Issue by L11K** [mangosango/clive#11]
Is it doable to implement a way for clive to only post clips to discord when X selected channels playing Y games? Like we can filter only to grab clips from mods/subs. I was reading the code and thought of editing certain places but it worked better in my head. If not doable, I can work with the keywords, like "Only post clip if it contains "master" in the message and was posted by a mod" sorry if I failed to be clear.

Thank you in advance for your time.

**Comment by jaredcat** [comment]
@L11K mod/subs is already implemented
The others doable and shouldn't be too hard, but going to be prone to user error.
