### ISSUE TITLE
No longer can pull twitch clips

### ISSUE THREAD

**Issue by hooptydoopty** [mangosango/clive#25]
get this error whenever a new clip is created and clive attempts to post to discord

  level: 'error',
  message: "ERROR: GET twitch API:Cannot read property 'title' of undefined",
  stack: "TypeError: Cannot read property 'title' of undefined\n" +
    '    at C:\\Clive\\src\\index.js:152:22',
  timestamp: '2021-09-17T18:20:03.836Z'

**Comment by jaredcat** [comment]
@hooptydoopty there were some changes on Twitch's side that broke this project. A lot of changes and fixes were just merged, so try it again!

Feel free to open a new issue if you run into any problems
