### ISSUE TITLE
Got this error after a clip is put in chat

### ISSUE THREAD

**Issue by YukiRainee** [mangosango/clive#9]
As the title says this error happens after a clip

>>> https://clips.twitch.tv/PrettiestCrispyAlmondYouDontSay <<<
thats the clip i am attempting to use clive with

debug: NEW MESSAGE:
 {"channel":"#brettdoesgaming","userstate":{"badges":{"bits-leader":"1"},"color":"#0000FF","display-name":"Excel101","emotes":null,"id":"bca8b4ea-4635-43b6-8807-b1d13602f561","mod":false,"room-id":"49651280","subscriber":false,"tmi-sent-ts":"1524114571878","turbo":false,"user-id":"49362490","user-type":null,"emotes-raw":null,"badges-raw":"bits-leader/1","username":"excel101","message-type":"chat"},"timestamp":"2018-04-19T05:09:31.916Z"}
[05:09] info: [#brettdoesgaming] <mrmariobrosftw>: https://clips.twitch.tv/PrettiestCrispyAlmondYouDontSay
debug: NEW MESSAGE:
 {"channel":"#brettdoesgaming","userstate":{"badges":{"moderator":"1","subscriber":"0","bits-leader":"3"},"color":"#952197","display-name":"MrMarioBrosFTW","emotes":null,"id":"cc947d92-d1e9-4fc9-b6dd-f36d2c1557d0","mod":true,"room-id":"49651280","subscriber":true,"tmi-sent-ts":"1524114584407","turbo":false,"user-id":"49262317","user-type":"mod","emotes-raw":null,"badges-raw":"moderator/1,subscriber/0,bits-leader/3","username":"mrmariobrosftw","message-type":"chat"},"timestamp":"2018-04-19T05:09:44.449Z"}
debug: CLIP DETECTED: in message: https://clips.twitch.tv/PrettiestCrispyAlmondYouDontSay {"timestamp":"2018-04-19T05:09:44.451Z"}
debug: URLs FOUND: 1 urls:  {"0":"https://clips.twitch.tv/PrettiestCrispyAlmondYouDontSay","timestamp":"2018-04-19T05:09:44.453Z"}
debug: CLIP SLUG: PrettiestCrispyAlmondYouDontSay {"timestamp":"2018-04-19T05:09:44.463Z"}
info: GET: /clips?id=PrettiestCrispyAlmondYouDontSay {"timestamp":"2018-04-19T05:09:44.468Z"}
debug: Twitch clip results: {"id":"PrettiestCrispyAlmondYouDontSay","url":"https://clips.twitch.tv/PrettiestCrispyAlmondYouDontSay","embed_url":"https://clips.twitch.tv/embed?clip=PrettiestCrispyAlmondYouDontSay","broadcaster_id":"49651280","creator_id":"110349947","video_id":"251994271","game_id":"","language":"en","title":"Nate, the expert pilot.","view_count":2,"created_at":"2018-04-19T04:44:35Z","thumbnail_url":"https://clips-media-assets.twitch.tv/227303671-preview-480x272.jpg","timestamp":"2018-04-19T05:09:44.563Z"}
info: GET: /users?id=110349947 {"timestamp":"2018-04-19T05:09:44.565Z"}
info: GET: /users?id=49651280 {"timestamp":"2018-04-19T05:09:44.567Z"}
info: GET: /games?id= {"timestamp":"2018-04-19T05:09:44.568Z"}
debug: DEBUG: Async results:
 {"0":{"id":"110349947","login":"narobicyt","display_name":"NarobicYT","type":"","broadcaster_type":"","description":"YouTube.com/NarobicYT","profile_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/narobicyt-profile_image-9bdc19e483e21135-300x300.png","offline_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/narobicyt-channel_offline_image-629de6fec7fc45c1-1920x1080.png","view_count":62},"1":{"id":"49651280","login":"brettdoesgaming","display_name":"BrettDoesGaming","type":"","broadcaster_type":"affiliate","description":"I'm a crazy College Kid who plays games cause that is what he likes to do!","profile_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/080daf80b8e6202a-profile_image-300x300.png","offline_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/b7be9f67936024e5-channel_offline_image-1920x1080.png","view_count":31022},"timestamp":"2018-04-19T05:09:44.669Z"}
(node:723) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'box_art_url' of undefined
    at buildMessage (/home/noire/clive/index.js:363:27)
    at Promise.all.then.results (/home/noire/clive/index.js:186:23)
    at <anonymous>
(node:723) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:723) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by THEDARKK** [comment]
Hello, I use it for 6 months, I have no bug.
Have you solved the problem?

**Comment by jaredcat** [comment]
Sorry I didn't see this earlier. The issue here is the clip didn't have a game associated with it (guessing you were streaming without setting the game).
I just pushed a fix to my fork and it'll be here next time @mangosango merges it from https://github.com/mangosango/clive/pull/10

**Comment by jaredcat** [comment]
@Rainee4563 https://github.com/mangosango/clive/pull/10 was merged. pull the latest master and it should be fixed
